canonical/self-signed-certificates-operator

- .github/workflows/publish-charm.yaml
- .github/workflows/push.yaml
Passes the charmcraft token as a variable to the publish workflow.
Reason: Environment Secrets are not available on Reusable Workflow
> Passes the charmcraft token as a variable to the publish workflow

- .github/workflows/integration-test.yaml
Uses LXD 5.13 for integration tests. Integration tests were crashing because the snap for 5.12 is not available anymore.
> [chore] Uses LXD 5.13 for integration tests

- .github/workflows/integration-test.yaml
- src/charm.py
- tests/unit/test_charm.py
Checks that ca certificate secret already exists before creating it. This fixes bug where charm would crash on follow-up config changed events. Fixes #7
> [Bug fix] Checks that ca certificate secret already exists before creating it

- .github/workflows/check-libraries.yaml
- .github/workflows/main.yaml
- .github/workflows/publish-charm.yaml
Runs the CI on a schedule each week to build and publish the charm.
The CI will run every Sunday at midnight UTC.
> Run the CI on a schedule

- config.yaml
- src/charm.py
- tests/unit/test_charm.py
- tox.ini
Handles the expiration of the Juju secret that stores the Root CA, and generates a new one when expired.
> Adds logic for Root CA renewal

- tests/integration/test_integration.py
Adds requirer charm to the integration tests:
- Checks if certificate is provided using the get-certificate action of the tls-requirer-operator charm
> Adds requirer charm to the integration tests

- README.md
- charmcraft.yaml
- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/mutual_tls_interface/v0/mutual_tls.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- tests/unit/test_send_ca_cert.py
- tox.ini
This PR adds a `mtls` relation for forwarding the ca cert.
Fixes #21.
This way, traefik won't need to send a CSR to the local-ca in order to obtain the ca cert (traefik needs the ca cert to load-balance https endpoints):
```mermaid
graph LR
external-ca ---|tls-certificates| traefik
subgraph your-model
traefik ---|ingress| your-app
your-app ---|tls-certificates| local-ca
traefik ---|send-ca-cert| local-ca
end
```
([Edit a copy of this diagram](https://mermaid.live/edit#pako:eNp1kLFqAzEMhl_l0Hx-gZvbLV3arWhRbV1iasvGliEhybvHcbhSAtmE9H2_kM5gk2NYYF8oH6bdJwoKH5WLUDCWJmPMRUM1lov61VtSrpdJC_Hqf1Fq-3mYp9SKiT0roEzbfNhe9oVrlwZCOd-BrX6RH5Id65-zKovr7UH_p3obBWaIXCJ51-8531UEPXBkhKWXjldqQRFQrh1t2fVd785rKrCsFCrPQE3T10ksLFoab9Cbp35k_KN4SB-Px43_zZBJvlPamOsNL3x6JA))
> Add send-ca-cert (certificate_transfer) relation

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/unit/test_charm.py
This fixes the bug with the action `get-issued-certificates`. The problem occurred when setting the results of the event, the expected data structure was a Dict[str, str], but the given was a nested dict. This PR converts the nested dicts into a formatted string.
> FIX: get-issued-certificates

- README.md
- actions.yaml
- src/charm.py
- tests/unit/test_charm.py
This change adds an action that returns the CA cert. This is needed in order to connect to the charms using certs generated by this charm.
> add get_ca action

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
This PR aims to fix https://github.com/canonical/self-signed-certificates-operator/issues/24 by bumping the library version to include the fix and it also adds tests for validation. Scale up operation does not crash the charm, after scaling a non-leader unit in this charm doesn't do anything.
> Update tls_certificates_interface lib to fix permission deny error during scale operation

- .github/workflows/integration-test.yaml
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Bumps the `tls_certificates` library to add the `KeyUsage` extension to the generated CA certificate.
> FIX: Add KeyUsage extension to CA certificate

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/unit/test_charm.py
This PR adds supports to generate a CA certificate. It is dependent on the following PR's being merged first:
- https://github.com/canonical/charm-relation-interfaces/pull/118
- https://github.com/canonical/tls-certificates-interface/pull/83
> feat: Adds supports to generate a CA certificate

- charmcraft.yaml
Adds support for building the charm for arm64. Currently does not automatically build or publish the charm for that architecture.
> feat: Add arm64 architecture support

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/unit/test_charm.py
Handles outstanding cerfificate requests in main hook and gets rid of `event.defer()`. This PR depends on the following PR being merged first: 
- https://github.com/canonical/tls-certificates-interface/pull/87
> feat: Handles outstanding cerfificate requests in main hook

- src/charm.py
- tests/unit/test_charm.py
This PR fixes an issue in tests where the content wasn't refreshed when getting a secret and it was possible to retrieve an old version of a secret instead of the latest one.
> fix: Refreshes secret content before getting its content

- .github/workflows/integration-test.yaml
- .github/workflows/publish-charm.yaml
Bumps actions workflow to v4. This should remove the need for the following PR's which are failing because they have been pushed separately instead of combined:
- PR #47 
- PR #48 
There seems to be this intermittent issue with v4 that I experienced here. We may want to pause before merging this PR:
https://github.com/actions/download-artifact/issues/249
> chore: Bumps artefact actions to v4

- tests/integration/test_integration.py
The tls-certificates requirer doesn't store ca chains anymore and won't return them in the `get-certificate` juju action (reference below). Here when we run the `get-certificate` action, we don't look at the ca chain anymore. This fixes an issue currently in main that prevents integration tests from running correctly.
- https://github.com/canonical/tls-certificates-requirer-operator/pull/39
> fix: Remove chain validation from integration tests

- .github/workflows/main.yaml
Passes CHARMCRAFT_AUTH secret to check-libraries.yaml workflow.
This should fix failing CI on dependabot PRs.
> fix: Passes CHARMCRAFT_AUTH secret to check-libraries.yaml workflow

- charmcraft.yaml
Build Python packages from source instead of using `binary-python-packages`. This fixes an issue with the current build in main.
```
::    ::   error: subprocess-exited-with-error
::    ::
::    ::   × Preparing metadata (pyproject.toml) did not run successfully.
::    ::   │ exit code: 1
::    ::   ╰─> [6 lines of output]
::    ::
::    ::       Cargo, the Rust package manager, is not installed or is not on PATH.
::    ::       This package requires Rust and Cargo to compile extensions. Install it through
::    ::       the system's package manager or via https://rustup.rs/
::    ::
```
- [CI failure in `main`](https://github.com/canonical/self-signed-certificates-operator/actions/runs/7899097564/job/21566024034)
> fix: Build Python packages from source instead of using `binary-python-packages`

- src/charm.py
- tests/integration/certificates.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
There is a bug where on ca common name config changed, the self-signed certificates charm would generate a new CA, store it in a secret but we would read the secret in the same event handler and it would be the old secret.
Now, we return after changing the root CA certificate and updating the secret and we observe the "secret_changed" event. This allows for reading the new ca certificate instead of reading the old one. 
Fixes #132
> fix: generate new ca cert on config changed

- .github/workflows/build.yaml
- .github/workflows/integration-test.yaml
- .github/workflows/publish-charm.yaml
- tests/integration/test_integration.py
This updates the CI to automatically build, test and upload the charm for arm64. It uses self-hosted arm64 runners for the arm64 specific jobs.
> chore: Automatically build charm for arm64

- src/charm.py
- tests/integration/certificates.py
- tests/integration/conftest.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
- tox.ini
Currently, ruff is only configured to check the files for linting errors. This adds ruff formatting to tox checks.
Review notes:
Only tox.ini contains functional changes, the rest are the result of running tox -e format.
> style: Format using ruff

- src/certificates.py
- src/charm.py
Move method requiring cryptography to the file where other cryptography related tasks are done. This way we don't need to know anything about certs and cryptography in the charm class anymore.
> refactor: move method requiring cryptography to the appropriate file

- src/certificates.py
- src/charm.py
- tests/unit/test_certificates.py
Respect root ca validity config option. We also remove the "default" value in the `generate_certificate` helpers to make sure the charm always provides a value. 
Fixes #213
> fix: respect root ca validity config option

- src/charm.py
- tests/unit/test_charm.py
The expiry of the secret holding the root ca should be equal to the root ca expiry.
Fixes #214
> fix: Fixes secret expiry to use the correct config value

- charmcraft.yaml
- src/charm.py
- tests/unit/test_charm.py
No attributes were configurable for the CA certificate. By default, the country was set to `US` however. Here we remove this default and allow users to configure their CA certificate attributes.
> feat: add CA certificate attribute config options

- charmcraft.yaml
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- src/charm.py
- src/constants.py
- tests/integration/test_integration.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_get_ca_certificate.py
- tests/unit/test_charm_get_issued_certificates.py
Fixes #238, #239 and #241 
- This PR implements the renewal of the CA certificate
- It handles CA certificate configuration option changes
- It keeps track of two CA certificates, one active and one expiring CA certificate.
- Improves validity time configs to allow units, inspired by #236 @kayra1
> feat: Implement CA certificate renewal

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/test_charm_configure.py
> chore: Use tls lib V4.0

- .github/renovate.json5
This configuration change will make Renovate use conventional commit messages.
> fix: Force Renovate to use conventional commit messages

- .github/renovate.json5
- .github/workflows/build.yaml
- .github/workflows/integration-test.yaml
Rollback concierge introduction to fix CI flakiness. Also prevent renovate from updating pytest-asyncio as it breaks integration tests.
> chore: Fix CI flakiness by rolling back concierge and preventing pytest-asyncio updates

- src/charm.py
This should remove the following deprecation warning:
```
unit-self-signed-certificates-0: 15:23:29 WARNING unit.self-signed-certificates/0.update-status /var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py:525: DeprecationWarning: Calling `ops.main.main()` is deprecated, call `ops.main()` instead
```
> refactor: Use `ops.main` instead of `ops.main.main`, the latter is deprecated

- pyproject.toml
- src/charm.py
- tests/integration/test_integration.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_get_issued_certificates.py
- tests/unit/test_charm_rotate_private_key.py
This change adds a pyright check to ensure that we add type hints to our code
> build: Enable pyright to check if type hints are missing

- tox.ini
Use uv sync in tox to use locked versions. This ensures that tox will not install newer packages when running.
> fix: Use uv sync in tox to use locked versions

- .github/workflows/main.yaml
- README.md
This charms builds for multiple architectures so we need to also publish for multiple architectures.
> fix: Use multiarch publish workflow

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/main.yaml
- .github/workflows/promote.yaml
I created a new branch for the old track (confusingly named `latest`) -- https://github.com/canonical/self-signed-certificates-operator/tree/latest
With these changes:
- This branch (`main`) should now publish to the `1/` track.
- The promote workflow should promote from and to the `1/` track.
> build: update track-name in publish workflow to version 1

- .github/workflows/issues.yaml
Replace legacy Jira URL with Webhook URL and Token in the issues (Jira Sync) workflow
> chore: Replace legacy Jira URL with Webhook URL and Token in the issues (Jira Sync) workflow

- terraform/versions.tf
`~>` in the TF provider version allows only the right-most version component to increment. Examples:
-   `~> 1.0.4`: Allows Terraform to install 1.0.5 and 1.0.10 but not 1.1.0.
-   `~> 1.1`: Allows Terraform to install 1.2 and 1.10 but not 2.0.
Here we make it possible for users to use Juju TF provider version `0.x.y`. 
A user asked us to use self-signed certificates with the TF provider 0.19 and we don't necessarily want to remove support for 0.18.
> chore: allow different tf provider minor versions

- .github/workflows/tics.yaml
- tox.ini
Workflow was failing due to missing XML file. Also renamed the workflow since it is not a "k8s" specific one.
> fix: add xml report and rename tics workflow

- src/charm.py
- tests/unit/test_charm_configure.py
The [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-4.4.2) has a strict requirement on the chain having the leaf certificate first. This PR fixes the order of the chain.
**Caution**: This is a breaking change, it would break charms that "expect wrong order". For example it would OpenSearch ([here](https://github.com/canonical/opensearch-operator/blob/2/edge/lib/charms/opensearch/v0/opensearch_tls.py#L228))
In my opinion expecting the wrong order and depending on it is wrong and can be considered a bug in the charms doing that, which makes me more comfortable with making this breaking change, but we still need to be cautious.
> fix: Fixes chain order in charm

- charmcraft.yaml
Since provides endpoints can be non-optional, can the default value of `optional` is [false](https://canonical-charmcraft.readthedocs-hosted.com/stable/reference/files/charmcraft-yaml-file/#endpoint-role-endpoint-name-optional), these endpoints are assumed non-optional.
Set `optional` flag on provides endpoints to indicate correct optionality.
> fix: Add optional flags to provides endpoints

- .github/workflows/integration-test.yaml
Integration tests are failing on ARM because the self hosted runners are failing to bootstrap strictly confined microk8s. To workaround that we use a non-strictly confined microk8s which requires manually adding kubeconfig to Juju and since that can't be done using actions-operator we set up the environment manually.
> fix: Setup Juju and Microk8s manually

- .github/workflows/trivy.yaml
The scan for main should run when we push to main.
> fix: Run the scan workflow on push to main

- .github/workflows/tics.yaml
- .gitignore
Fetch the libs of the project before running the TiCS analysis.
> fix: Ensure fetch_libs is set to true in TiCS Static Analysis workflow
