CODEOWNERS, CONTRIBUTING.md
- Adds CODEOWNERS
- Fixes CONTRIBUTING.md errors
=> Adds CODEOWNERS

metadata.yaml
Add URLs to metadata so charmhub renders backlinks to the github repo.
=> Add URLs to metadata

lib/charms/tls_certificates_interface/v2/tls_certificates.py
=> [Chore] Bumps TLS lib version

README.md, actions.yaml, charmcraft.yaml, lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/charm.py, tests/unit/test_charm.py
Adds an action to get issued certificates using the `get_issued_certificates` function from the library.
=> Dev adds action to get issued certs

lib/charms/tls_certificates_interface/v2/tls_certificates.py
Updating TLS interface library to latest version (LIBPATCH 12).
=> Update TLS certificate interface version to 12

lib/charms/tls_certificates_interface/v2/tls_certificates.py
This bumps the `tls-certificates` library to the latest version to add extensions to generated certificates that will allow strict validation to pass.
=> Bump tls-certificates library version

.github/workflows/update-libs.yaml
Adds update-libs workflow to create PRs automaticaclly to update charm libraries.
The workflow will run every 12 hours.
=> feat: Adds update-libs workflow

lib/charms/tls_certificates_interface/v2/tls_certificates.py
Bumps the tls lib to 2.21.
Fixes #52
=> chore: Bumps tls lib to 2.21

.github/workflows/integration-test.yaml
bump juju version from 3.1 to 3.4.
=> chore: bump juju to 3.4

.github/workflows/dependabot_pr.yaml, .github/workflows/main.yaml, pyproject.toml, tests/integration/test_integration.py, tox.ini
- Automates dependabot PR review and merge
- Improves tox config and fixes related issues
- Adds concurrency job to cancel currently running CI actions when a new commit is pushed on the same branch. (Excludes main from this logic)
=> feat: Automates dependabot PR review and merge

.github/dependabot.yml
Adds `terraform` package-ecosystem to Dependabot's configuration
=> chore: Adding Terraform ecosystem for Dependabot

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/integration-test.yaml, .github/workflows/lint-report.yaml, .github/workflows/main.yaml, .github/workflows/promote.yaml, .github/workflows/publish-charm.yaml, .github/workflows/static-analysis.yaml, .github/workflows/unit-test.yaml, tests/integration/conftest.py, tests/integration/test_integration.py
We build the charm in an independent workflow step and we separate the CI workflows in simpler more focused files, just like we do in Vault charms.
=> chore: build charm in independent workflow step

lib/charms/tls_certificates_interface/v4/tls_certificates.py, src/charm.py, tests/unit/test_charm_configure.py
Bump tls lib to v4.6 to properly distribute CA Certificates. Depends on:
- https://github.com/canonical/tls-certificates-interface/pull/229
=> chore: bump tls lib to v4.6

.github/workflows/promote.yaml
Allows promoting the charm for arm64 arch, adds an arch selection.
Depends on #242
=> feat: Allows promoting the charm for arm64 arch

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, lib/charms/tls_certificates_interface/v4/tls_certificates.py, src/charm.py, tests/unit/test_charm_configure.py
- Tracing libs have been moved, this PR fetches the new ones.
- Fetches the latest tls lib
=> chore: Fetches the new tracing and the latest tls libs

.github/workflows/integration-test.yaml
=> chore: bump juju to 3.6/stable

.github/workflows/integration-test.yaml
Fixes tox installation in the integration tests
=> build: Fix tox installation in integration tests

.github/workflows/build.yaml, .github/workflows/integration-test.yaml, .github/workflows/main.yaml, .github/workflows/promote.yaml, charmcraft.yaml, terraform/main.tf, tests/integration/test_integration.py
In preparation for the `1/` release, bump the base to 24.04 to align with the latest Ubuntu LTS.
Closes #270
=> build: Update from Ubuntu 24.04 and shorthand charmcraft.yaml format

.github/renovate.json5
Run renovate on `main` and `latest` branch so that both releases are kept up to date.
=> build: Run renovate on main and latest branch

.github/workflows/tics.yaml
Adds a TiCS static analysis workflow to run every week, which is the maximum frequency recommend.
=> build: TiCS Static Analysis

lib/charms/certificate_transfer_interface/v1/certificate_transfer.py, lib/charms/tls_certificates_interface/v4/tls_certificates.py
Bumps charm libraries. Fixes #358
=> chore: Bump charm libraries

.github/renovate.json5, .github/workflows/integration-test.yaml
Allow renovate to update dependencies on release branch (`latest`)
=> feat: Allow renovate to update dependencies on release branch

.github/workflows/uv-scan.yaml
Run the scan workflow on the release branch `latest`.
It will scan the dependencies on every merge to the branch. This will run periodically because of the Renovate PRs.
=> feat: Run the uv scan workflow

.github/workflows/trivy.yaml
=> feat: Configure Trivy on main

.github/renovate.json5
=> fix: Fix syntax error

charmcraft.yaml
Use the shorthand notion syntax so the charm can be added to the charmcraft cache hub
=> chore: Use the shorthand notion syntax

.github/workflows/trivy.yaml
Set permissions explicitly when calling shared workflows
=> chore: Set permissions explicitly
